/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;

/**
 *
 * @author coste
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        txtComplejo1.requestFocusInWindow();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtComplejo1 = new javax.swing.JTextField();
        txtComplejo2 = new javax.swing.JTextField();
        txtComplejo3 = new javax.swing.JTextField();
        txtComplejo4 = new javax.swing.JTextField();
        cmbOperaciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        cmdLimpiar = new javax.swing.JButton();
        cmdResolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Complejos");
        setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtComplejo1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtComplejo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComplejo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 30, -1));

        txtComplejo2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtComplejo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComplejo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, -1));

        txtComplejo3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtComplejo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComplejo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 30, -1));

        txtComplejo4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtComplejo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtComplejo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 30, -1));

        cmbOperaciones.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 70));

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        cmdResolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdResolver.setText("Resolver");
        cmdResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResolverActionPerformed(evt);
            }
        });
        jPanel1.add(cmdResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 219));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        txtComplejo1.setText("");
        txtComplejo2.setText("");
        txtComplejo3.setText("");
        txtComplejo4.setText("");
        txtResultado.setText("");
        cmbOperaciones.setSelectedIndex(0);
        txtComplejo1.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResolverActionPerformed
        // TODO add your handling code here:
        int n, n1, n2, n3, n4, n5;
        Complejos c, c2, c3 = null;
        int op = cmbOperaciones.getSelectedIndex();

        n = Integer.parseInt(txtComplejo1.getText());
        n1 = Integer.parseInt(txtComplejo2.getText());
        n2 = Integer.parseInt(txtComplejo3.getText());
        n3 = Integer.parseInt(txtComplejo4.getText());

        try {
            c = new Complejos(n, n1);
            c2 = new Complejos(n2, n3);

            switch (op) {
                case 0:
                    c3 = c.suma(c2);
                    break;
                case 1:
                    c3 = c.resta(c2);
                    break;
                case 2:
                    c3 = c.multiplicacion(c2);
                    break;
                case 3:
                    c3 = c.division(c2);
                    break;
            }

        } catch (CeroException ex) {
            Helper.mensaje(null, "No se puede ingresar 0", "Error", 2);
        }

        txtResultado.setText("(" + c3.getN() + c3.getN1() + ")i");


    }//GEN-LAST:event_cmdResolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdResolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtComplejo1;
    private javax.swing.JTextField txtComplejo2;
    private javax.swing.JTextField txtComplejo3;
    private javax.swing.JTextField txtComplejo4;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
